# Generated by Django 2.2.9 on 2020-01-30 19:40

from django.db import migrations
from machina.conf import settings
if settings.SEARCH_ENGINE == 'postgres':
    import django.contrib.postgres.indexes
    import django.contrib.postgres.search


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0011_remove_post_poster_ip'),
    ]

    if settings.SEARCH_ENGINE == 'postgres':
        operations = [
            migrations.AddField(
                model_name='post',
                name='search_vector_all',
                field=django.contrib.postgres.search.SearchVectorField(null=True),
            ),
            migrations.AddField(
                model_name='post',
                name='search_vector_subject',
                field=django.contrib.postgres.search.SearchVectorField(null=True),
            ),
            migrations.AddIndex(
                model_name='post',
                index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_all'], name='forum_conve_search__8a09bd_gin'),
            ),
            migrations.AddIndex(
                model_name='post',
                index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_subject'], name='forum_conve_search__be2f8f_gin'),
            ),
            migrations.RunSQL(
                    sql='''
                    CREATE TRIGGER post_update_trigger_all
                    BEFORE INSERT OR UPDATE OF subject, content, search_vector_all
                    ON forum_conversation_post
                    FOR EACH ROW EXECUTE PROCEDURE
                    tsvector_update_trigger(
                      search_vector_all, 'pg_catalog.{0}', subject, content);

                    CREATE TRIGGER post_update_trigger_subject
                    BEFORE INSERT OR UPDATE OF subject, search_vector_subject
                    ON forum_conversation_post
                    FOR EACH ROW EXECUTE PROCEDURE
                    tsvector_update_trigger(
                      search_vector_subject, 'pg_catalog.{0}', subject);

                    UPDATE forum_conversation_post SET search_vector_all = NULL, search_vector_subject = NULL;
                    '''.format(settings.SEARCH_LANGUAGE),

                    reverse_sql='''
                    DROP TRIGGER IF EXISTS post_update_trigger_all, post_update_trigger_subject
                    ON forum_conversation_post;
                    '''),
        ]
    else:
        operations = []
