# Generated by Django 3.2.11 on 2022-04-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0013_auto_20201220_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='forum_conversatin.Post', verbose_name='Parent post'),
        ),
    ]
